Traceback (most recent call last):
  File "/Users/alex.cole/Documents/Hackbright/Week 1/Day 5/raisestatement.py", line 4, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
